name: Test functions

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test_functions:
    name: Test functions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uxsimpp and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Install pytest other dependencies
        run: pip install pytest pytest-rerunfailures pytest-xdist setuptools
      - name: Run verifications with pytest
        run: pytest -n auto tests/test_functions.py --durations=0 -v